// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADzGbb_x013UGAMreDE_52R7wQ4m6NEwA',
    appId: '1:1041576948012:web:e26aaebf4847f59d867c89',
    messagingSenderId: '1041576948012',
    projectId: 'medical-booking-app-e367f',
    authDomain: 'medical-booking-app-e367f.firebaseapp.com',
    storageBucket: 'medical-booking-app-e367f.firebasestorage.app',
    measurementId: 'G-0ZP2X0KZJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcx8cFm10Jy__HdqPu-X1wnboXKFTlgK0',
    appId: '1:1041576948012:android:025b667ea2bc3327867c89',
    messagingSenderId: '1041576948012',
    projectId: 'medical-booking-app-e367f',
    storageBucket: 'medical-booking-app-e367f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8NfVuA3MapINXkupsmWp2WRNbE8SEy4w',
    appId: '1:1041576948012:ios:da6177dc374fff81867c89',
    messagingSenderId: '1041576948012',
    projectId: 'medical-booking-app-e367f',
    storageBucket: 'medical-booking-app-e367f.firebasestorage.app',
    iosBundleId: 'com.example.bookingDoctorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8NfVuA3MapINXkupsmWp2WRNbE8SEy4w',
    appId: '1:1041576948012:ios:da6177dc374fff81867c89',
    messagingSenderId: '1041576948012',
    projectId: 'medical-booking-app-e367f',
    storageBucket: 'medical-booking-app-e367f.firebasestorage.app',
    iosBundleId: 'com.example.bookingDoctorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADzGbb_x013UGAMreDE_52R7wQ4m6NEwA',
    appId: '1:1041576948012:web:36ab8811bc19d682867c89',
    messagingSenderId: '1041576948012',
    projectId: 'medical-booking-app-e367f',
    authDomain: 'medical-booking-app-e367f.firebaseapp.com',
    storageBucket: 'medical-booking-app-e367f.firebasestorage.app',
    measurementId: 'G-BPEG0M9MBM',
  );
}
